packages:
  - frontend
  - backend
  - packages/contracts
  - packages/types
  - packages/utils

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@swc/core"
  - "@vercel/speed-insights"
  - bufferutil
  - esbuild
  - sharp
  - utf-8-validate
