packages:
  - frontend
  - backend
  - fx_utils

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@vercel/speed-insights'
  - bufferutil
  - esbuild
  - prisma
  - sharp
  - utf-8-validate
